/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 27 00:18:28 GMT 2018
 */

package mutated.tiny;

import org.junit.Test;
import static org.junit.Assert.*;


public class TestTinyTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
    TinyTest tinyTest0 = new TinyTest();
    boolean boolean0 = tinyTest0.tiny(0, 0, 0);
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
    TinyTest tinyTest0 = new TinyTest();
    boolean boolean0 = tinyTest0.tiny((-2540), (-2540), (-1));
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
    TinyTest tinyTest0 = new TinyTest();
    boolean boolean0 = tinyTest0.tiny((-449), (-21), (-21));
    assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
    TinyTest tinyTest0 = new TinyTest();
    boolean boolean0 = tinyTest0.tiny((-449), (-449), (-449));
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
    TinyTest tinyTest0 = new TinyTest();
    boolean boolean0 = tinyTest0.tiny((-449), (-21), (-449));
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
    TinyTest tinyTest0 = new TinyTest();
    boolean boolean0 = tinyTest0.tiny(4, 1, 5);
    assertFalse(boolean0);
  }
}
